"""create_meeting_transition_record_table

Revision ID: 0e8980438aa9
Revises: f234bcd56789
Create Date: 2025-10-01 10:15:40.451442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision: str = "0e8980438aa9"
down_revision: Union[str, None] = "f234bcd56789"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

meeting_status = pg.ENUM(
    "NONE",
    "CAPTURE_PENDING",
    "IMPORT_PENDING",
    "CAPTURE_BOT_IS_CONNECTING",
    "CAPTURE_BOT_CONNECTION_FAILED",
    "CAPTURE_IN_PROGRESS",
    "TRANSCRIPTION_PENDING",
    "TRANSCRIPTION_DONE",
    "REPORT_PENDING",
    "REPORT_DONE",
    "CAPTURE_FAILED",
    "TRANSCRIPTION_FAILED",
    name="meetingstatus",
    create_type=False,  # Important: use the existing type
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meeting_transition_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("estimated_end_date", sa.DateTime(), nullable=False),
        sa.Column("status_from", meeting_status, nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_transition_record_id"),
        "meeting_transition_record",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meeting_transition_record_id"), table_name="meeting_transition_record"
    )
    op.drop_table("meeting_transition_record")
    # ### end Alembic commands ###
