"""add-last-capture-audio-index

Revision ID: 1b957c30ebe4
Revises: 635bd3fef1bb
Create Date: 2025-06-10 13:54:51.164726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b957c30ebe4"
down_revision: Union[str, None] = "635bd3fef1bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting", sa.Column("last_captured_audio_index", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "last_captured_audio_index")
    # ### end Alembic commands ###
