"""add vote field to deliverable

Revision ID: 1dfb13692257
Revises: 717de2b78c2e
Create Date: 2026-04-01 10:24:55.721863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dfb13692257"
down_revision: str | None = "717de2b78c2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliverable", sa.Column("vote_type", sa.String(), nullable=True))
    op.add_column("deliverable", sa.Column("vote_comment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliverable", "vote_comment")
    op.drop_column("deliverable", "vote_type")
    # ### end Alembic commands ###
