"""add custom_prompt to deliverable

Revision ID: 26c0970cb677
Revises: c7e2a4f1b9d3
Create Date: 2026-07-22 15:22:49.633847

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26c0970cb677"
down_revision: str | None = "c7e2a4f1b9d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deliverable", sa.Column("custom_prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliverable", "custom_prompt")
    # ### end Alembic commands ###
