"""remove_meeting_audio_index

Revision ID: 309fda53987a
Revises: 3fa81afe2947
Create Date: 2025-08-07 15:35:38.246944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "309fda53987a"
down_revision: Union[str, None] = "3fa81afe2947"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "last_captured_audio_index")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting",
        sa.Column(
            "last_captured_audio_index",
            sa.INTEGER(),
            autoincrement=False,
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
