"""remove_meeting_type_and_agenda

Revision ID: 3fa81afe2947
Revises: 8eae6cd096cc
Create Date: 2025-08-05 17:26:45.941855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3fa81afe2947"
down_revision: Union[str, None] = "8eae6cd096cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meeting_meeting_type"), table_name="meeting")
    op.drop_column("meeting", "meeting_agenda")
    op.drop_column("meeting", "meeting_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting",
        sa.Column("meeting_type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "meeting",
        sa.Column(
            "meeting_agenda",
            postgresql.JSON(astext_type=sa.Text()),  # type: ignore[no-untyped-call]
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_meeting_meeting_type"), "meeting", ["meeting_type"], unique=False
    )
    # ### end Alembic commands ###
