"""mark_fields_as_non_null

Revision ID: 5df0f2d291e0
Revises: 1b957c30ebe4
Create Date: 2025-07-28 14:20:32.081501

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5df0f2d291e0"
down_revision: Union[str, None] = "1b957c30ebe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure that possibly null values have a default value
    meeting = sa.table(
        "meeting",
        sa.column("user_id", sa.Integer),
        sa.column("last_captured_audio_index", sa.Integer),
    )

    transcription = sa.table(
        "transcription",
        sa.column("version", sa.Integer),
    )

    user = sa.table("user", sa.column("keycloak_uuid"), sa.column("id"))
    first_user_id = op.get_bind().execute(sa.select(user.c.id).limit(1)).scalar()

    if first_user_id is not None:
        op.execute(
            meeting.update()
            .where(meeting.c.user_id.is_(None))
            .values(user_id=first_user_id)
        )
    op.execute(
        meeting.update()
        .where(meeting.c.last_captured_audio_index.is_(None))
        .values(last_captured_audio_index=0)
    )
    op.execute(
        transcription.update()
        .where(transcription.c.version.is_(None))
        .values(version=0)
    )
    op.execute(
        user.update()
        .where(user.c.keycloak_uuid.is_(None))
        .values(keycloak_uuid="00000000-0000-4000-8000-000000000000")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("meeting", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "meeting",
        "last_captured_audio_index",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "transcription",
        "transcription_index",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "transcription", "speaker", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "transcription", "transcription", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "transcription", "version", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "transcription", "meeting_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("user", "keycloak_uuid", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user",
        "role",
        existing_type=postgresql.ENUM("ADMIN", "USER", name="role"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "role",
        existing_type=postgresql.ENUM("ADMIN", "USER", name="role"),
        nullable=True,
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("user", "keycloak_uuid", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "transcription", "meeting_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "transcription", "version", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "transcription", "transcription", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "transcription", "speaker", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "transcription",
        "transcription_index",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "meeting",
        "last_captured_audio_index",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("meeting", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
