"""remove User password

Revision ID: 635bd3fef1bb
Revises: b0cea6a22be0
Create Date: 2025-06-11 16:19:59.449015

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "635bd3fef1bb"
down_revision: Union[str, None] = "b0cea6a22be0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
