"""rename_meeting_transcription_record_fields

Revision ID: 67abf415a659
Revises: 37e431c19a4d
Create Date: 2025-11-21 12:42:30.362410

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67abf415a659"
down_revision: Union[str, None] = "37e431c19a4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename columns instead of dropping and recreating
    op.alter_column(
        "meeting_transition_record",
        "start_date",
        new_column_name="timestamp",
    )
    op.alter_column(
        "meeting_transition_record",
        "estimated_end_date",
        new_column_name="predicted_date_of_next_transition",
    )
    op.alter_column(
        "meeting_transition_record",
        "status_from",
        new_column_name="status",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename columns back to their original names
    op.alter_column(
        "meeting_transition_record",
        "status",
        new_column_name="status_from",
    )
    op.alter_column(
        "meeting_transition_record",
        "predicted_date_of_next_transition",
        new_column_name="estimated_end_date",
    )
    op.alter_column(
        "meeting_transition_record",
        "timestamp",
        new_column_name="start_date",
    )
    # ### end Alembic commands ###
