"""remove end_date

Revision ID: 7648031b6206
Revises: beec5d6f2075
Create Date: 2025-05-09 09:37:30.467918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7648031b6206"
down_revision: Union[str, None] = "beec5d6f2075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meeting_end_date", table_name="meeting")
    op.drop_column("meeting", "end_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting",
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.create_index("ix_meeting_end_date", "meeting", ["end_date"], unique=False)
    # ### end Alembic commands ###
