"""merge-meeting-statuses

Revision ID: 7996ad5c1d8d
Revises: 7648031b6206
Create Date: 2025-05-23 11:07:46.047062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7996ad5c1d8d"
down_revision: Union[str, None] = "7648031b6206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_meeting_status = sa.Enum(
    "NONE",
    "CAPTURE_PENDING",
    "CAPTURE_IN_PROGRESS",
    "TRANSCRIPTION_PENDING",
    "TRANSCRIPTION_DONE",
    "CAPTURE_FAILED",
    "TRANSCRIPTION_FAILED",
    name="meetingstatus",
)

old_meeting_status = sa.Enum(
    "PENDING", "IN_PROGRESS", "DONE", "FAILED", name="meetingstatus"
)


capture_status = sa.Enum(
    "NONE", "PENDING", "IN_PROGRESS", "DONE", "FAILED", name="capturestatus"
)


transcription_status = sa.Enum(
    "NONE",
    "PENDING",
    "IN_PROGRESS",
    "DONE",
    "FAILED",
    name="transcriptionstatus",
)


def upgrade() -> None:
    op.drop_column("meeting", "capture_status")
    op.drop_column("meeting", "transcription_status")
    op.drop_column("meeting", "status")

    old_meeting_status.drop(op.get_bind(), checkfirst=True)  # type: ignore
    capture_status.drop(op.get_bind(), checkfirst=True)  # type: ignore
    transcription_status.drop(op.get_bind(), checkfirst=True)  # type: ignore

    new_meeting_status.create(op.get_bind(), checkfirst=False)  # type: ignore

    op.add_column(
        "meeting",
        sa.Column(
            "status",
            new_meeting_status,
            server_default="NONE",
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_column("meeting", "status")
    new_meeting_status.drop(op.get_bind(), checkfirst=True)  # type: ignore

    old_meeting_status.create(op.get_bind(), checkfirst=True)  # type: ignore
    capture_status.create(op.get_bind(), checkfirst=True)  # type: ignore
    transcription_status.create(op.get_bind(), checkfirst=True)  # type: ignore
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting",
        sa.Column(
            "transcription_status",
            transcription_status,
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "meeting",
        sa.Column(
            "capture_status",
            capture_status,
            autoincrement=False,
            nullable=True,
        ),
    )

    op.add_column(
        "meeting",
        sa.Column(
            "status",
            old_meeting_status,
            autoincrement=False,
            nullable=True,
        ),
    )
