"""remove_audio_index

Revision ID: 8eae6cd096cc
Revises: 5df0f2d291e0
Create Date: 2025-07-28 15:48:46.613593

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eae6cd096cc"
down_revision: Union[str, None] = "5df0f2d291e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcription_audio_segment_index", table_name="transcription")
    op.drop_column("transcription", "audio_segment_index")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription",
        sa.Column(
            "audio_segment_index", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_index(
        "ix_transcription_audio_segment_index",
        "transcription",
        ["audio_segment_index"],
        unique=False,
    )
    # ### end Alembic commands ###
