"""add_start_and_end_date

Revision ID: 9aa89891354a
Revises: 2183b593393d
Create Date: 2025-12-23 15:52:55.485541

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aa89891354a"
down_revision: Union[str, None] = "2183b593393d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="meeting", column_name="start_date", new_column_name="creation_date"
    )
    op.execute("ALTER INDEX ix_meeting_start_date RENAME TO ix_meeting_creation_date")
    op.add_column("meeting", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("meeting", sa.Column("end_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "end_date")
    op.drop_column("meeting", "start_date")
    op.execute("ALTER INDEX ix_meeting_creation_date RENAME TO ix_meeting_start_date")
    op.alter_column(
        table_name="meeting",
        column_name="creation_date",
        new_column_name="start_date",
    )
    # ### end Alembic commands ###
