"""remove_transcription_version

Revision ID: ad716383829e
Revises: 9ad682c0d475
Create Date: 2025-08-11 17:56:07.499522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad716383829e"
down_revision: Union[str, None] = "9ad682c0d475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription", "version")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription",
        sa.Column(
            "version", sa.INTEGER(), autoincrement=False, nullable=True, default=0
        ),
    )
    # ### end Alembic commands ###
