"""add keycloak_uuid

Revision ID: b0cea6a22be0
Revises: 7996ad5c1d8d
Create Date: 2025-05-27 18:36:20.460175

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0cea6a22be0"
down_revision: Union[str, None] = "7996ad5c1d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("keycloak_uuid", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_user_keycloak_uuid"), "user", ["keycloak_uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_keycloak_uuid"), table_name="user")
    op.drop_column("user", "keycloak_uuid")
    # ### end Alembic commands ###
