"""add cascade delete

Revision ID: bbf0d24b3bc4
Revises: 4774a95810b3
Create Date: 2025-10-13 10:43:52.030472

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbf0d24b3bc4"
down_revision: Union[str, None] = "4774a95810b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("meeting_transition_record_meeting_id_fkey"),
        "meeting_transition_record",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "meeting_transition_record",
        "meeting",
        ["meeting_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("transcription_meeting_id_fkey"), "transcription", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "transcription", "meeting", ["meeting_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transcription", type_="foreignkey")
    op.create_foreign_key(
        op.f("transcription_meeting_id_fkey"),
        "transcription",
        "meeting",
        ["meeting_id"],
        ["id"],
    )
    op.drop_constraint(None, "meeting_transition_record", type_="foreignkey")
    op.create_foreign_key(
        op.f("meeting_transition_record_meeting_id_fkey"),
        "meeting_transition_record",
        "meeting",
        ["meeting_id"],
        ["id"],
    )
    # ### end Alembic commands ###
