"""baseline

Revision ID: beec5d6f2075
Revises:
Create Date: 2025-05-12 16:58:33.438823

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beec5d6f2075"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_member_id"), "member", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("entity_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="role"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_entity_name"), "user", ["entity_name"], unique=False)
    op.create_index(op.f("ix_user_first_name"), "user", ["first_name"], unique=False)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_last_name"), "user", ["last_name"], unique=False)
    op.create_table(
        "meeting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("name_platform", sa.String(), nullable=True),
        sa.Column("meeting_type", sa.String(), nullable=True),
        sa.Column("meeting_agenda", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "DONE", "FAILED", name="meetingstatus"),
            nullable=True,
        ),
        sa.Column(
            "capture_status",
            sa.Enum(
                "NONE", "PENDING", "IN_PROGRESS", "DONE", "FAILED", name="capturestatus"
            ),
            nullable=True,
        ),
        sa.Column(
            "transcription_status",
            sa.Enum(
                "NONE",
                "PENDING",
                "IN_PROGRESS",
                "DONE",
                "FAILED",
                name="transcriptionstatus",
            ),
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("meeting_platform_id", sa.String(), nullable=True),
        sa.Column("meeting_password", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meeting_end_date"), "meeting", ["end_date"], unique=False)
    op.create_index(op.f("ix_meeting_id"), "meeting", ["id"], unique=False)
    op.create_index(
        op.f("ix_meeting_meeting_type"), "meeting", ["meeting_type"], unique=False
    )
    op.create_index(op.f("ix_meeting_name"), "meeting", ["name"], unique=False)
    op.create_index(
        op.f("ix_meeting_name_platform"), "meeting", ["name_platform"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_start_date"), "meeting", ["start_date"], unique=False
    )
    op.create_index(op.f("ix_meeting_url"), "meeting", ["url"], unique=False)
    op.create_table(
        "list_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["meeting_id"], ["meeting.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["member.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_list_participants_id"), "list_participants", ["id"], unique=False
    )
    op.create_table(
        "transcription",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audio_segment_index", sa.Integer(), nullable=True),
        sa.Column("transcription_index", sa.Integer(), nullable=True),
        sa.Column("speaker", sa.String(), nullable=True),
        sa.Column("transcription", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("meeting_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcription_audio_segment_index"),
        "transcription",
        ["audio_segment_index"],
        unique=False,
    )
    op.create_index(op.f("ix_transcription_id"), "transcription", ["id"], unique=False)
    op.create_index(
        op.f("ix_transcription_speaker"), "transcription", ["speaker"], unique=False
    )
    op.create_index(
        op.f("ix_transcription_transcription"),
        "transcription",
        ["transcription"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcription_transcription_index"),
        "transcription",
        ["transcription_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transcription_transcription_index"), table_name="transcription"
    )
    op.drop_index(op.f("ix_transcription_transcription"), table_name="transcription")
    op.drop_index(op.f("ix_transcription_speaker"), table_name="transcription")
    op.drop_index(op.f("ix_transcription_id"), table_name="transcription")
    op.drop_index(
        op.f("ix_transcription_audio_segment_index"), table_name="transcription"
    )
    op.drop_table("transcription")
    op.drop_index(op.f("ix_list_participants_id"), table_name="list_participants")
    op.drop_table("list_participants")
    op.drop_index(op.f("ix_meeting_url"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_start_date"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_name_platform"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_name"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_meeting_type"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_id"), table_name="meeting")
    op.drop_index(op.f("ix_meeting_end_date"), table_name="meeting")
    op.drop_table("meeting")
    op.drop_index(op.f("ix_user_last_name"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_first_name"), table_name="user")
    op.drop_index(op.f("ix_user_entity_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_member_id"), table_name="member")
    op.drop_table("member")
    # ### end Alembic commands ###
