"""add_report_filename

Revision ID: ca74396de706
Revises: ed12f9c61fe4
Create Date: 2025-08-22 14:41:06.232206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca74396de706"
down_revision: Union[str, None] = "ed12f9c61fe4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meeting", sa.Column("report_filename", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "report_filename")
    # ### end Alembic commands ###
