"""add notes to meeting

Revision ID: e57b5e520610
Revises: c3a1f0d8e2b4
Create Date: 2026-05-06 12:14:34.577445

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e57b5e520610"
down_revision: str | None = "c3a1f0d8e2b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("feedback", "vote_type", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("meeting", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting", "notes")
    op.alter_column("feedback", "vote_type", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
