"""constrain_name_platform

Revision ID: ed12f9c61fe4
Revises: ad716383829e
Create Date: 2025-08-19 18:11:52.261542

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from mcr_meeting.app.models.meeting_model import MeetingPlatforms

# revision identifiers, used by Alembic.
revision: str = "ed12f9c61fe4"
down_revision: Union[str, None] = "ad716383829e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


platform_name = sa.Enum(
    MeetingPlatforms,
    name="meetingplatforms",
)

platform_name_list = [platform.value for platform in MeetingPlatforms]


def upgrade() -> None:
    platform_name.create(op.get_bind(), checkfirst=False)  # type: ignore

    meeting = sa.table(
        "meeting",
        sa.column("name_platform", sa.VARCHAR),
    )

    op.execute(
        meeting.update()
        .where(
            ~meeting.c.name_platform.in_(platform_name_list)
            | meeting.c.name_platform.is_(None)
        )
        .values(name_platform="COMU")
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meeting",
        "name_platform",
        existing_type=sa.VARCHAR(),
        type_=platform_name,
        nullable=False,
        postgresql_using="name_platform::meetingplatforms",
    )
    op.drop_index(op.f("ix_meeting_name_platform"), table_name="meeting")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_meeting_name_platform"), "meeting", ["name_platform"], unique=False
    )
    op.alter_column(
        "meeting",
        "name_platform",
        existing_type=platform_name,
        type_=sa.VARCHAR(),
        nullable=True,
    )

    platform_name.drop(op.get_bind(), checkfirst=False)  # type: ignore

    # ### end Alembic commands ###
